### ISSUE TITLE
Ошибочки

### ISSUE THREAD

**Issue by weter1981** [ziggi/Open-GTO#1]
Можно как нибудь уже исправленные файлы получить?

**Comment by weteroks** [comment]
зиггииии, доброго времени еще незабросил?
cmdlist -укнов команд, скрипты все отключал непомогает, админка есть ркон так же непомог что делать

**Comment by ziggi** [comment]
@weter1981 какую версию используешь?

**Comment by weteroks** [comment]
Добрый день уважаемый зиги
саустя много времени решил поднять сервер опен гто но возникла проблема со входом бота на сервер
samp-server_alpha версии 0.3.6 бот конектится и заходит в игру
на samp srver 0.3.7 ни вкакую помогите разобраться

в консоли скрипт загружается
