### ISSUE TITLE
Добавить возможность игроку смотреть статистику другого игрока

### ISSUE THREAD

**Issue by ziggi** [ziggi/Open-GTO#10]
В окне, вызываемом через Tab добавить пункт информации о другом игроке. Нужно выводить всю информацию о нём, включая количество банов, киков, мутов и предупреждений.

**Comment by thetruesteepname** [comment]
по-моему, это не нужно, особенно для обычных игроков, не каждый хочет, чтобы его статистика была полностью просматриваемая другими, обычными игроками, хотя бы потому что когда я меняю ник, это может означать, что либо мне не нравится мое старое имя, либо то что я хочу скрыться

**Comment by ziggi** [comment]
Спасибо, согласен.
