### ISSUE TITLE
Передача оружия

### ISSUE THREAD

**Issue by ziggi** [ziggi/Open-GTO#11]
Сделать команду + диалог передачи оружия другому игроку.

**Comment by thetruesteepname** [comment]
явный дисбаланс, как и по прокачке, так и по множеству других параметров, к примеру - даешь РПГ своему другу с 1 уровнем, он начинает унижать твоих противников, при этом не с такими потерями как ты, на своем уровне, к тому же неплохо поднимается вверх по уровню

вариантов 2, ограничение каким-либо способом, либо не делать это вообще

**Comment by ziggi** [comment]
Не подумал про это, согласен.
