### ISSUE TITLE
Исправить спектатор

### ISSUE THREAD

**Issue by ziggi** [ziggi/Open-GTO#13]
Сделать так, чтобы после выхода из режима спектатора игрок появлялся на прошлом месте с тем-же оружием, количеством здоровья и бронёй.

**Comment by thetruesteepname** [comment]
лучше сделать все тоже самое, но чтобы появлялся не на том же месте, а на спавне, ибо от низко интеллектуальных игроков будут визги, мол тп, кто по умнее будет кричать, что ты делаешь это через админку, кто же нет - через читы, да и нормальных игроков могу спугнуть резкие появления админов перед ними, как и доставить дискомфорт самим админам, если их эти игроки убьют
