### ISSUE TITLE
Аксессуары в магазине одежды

### ISSUE THREAD

**Issue by ziggi** [ziggi/Open-GTO#21]
Добавить возможность покупки очков, головных уборов, часов и прочей атрибутики в магазине одежды.

**Comment by thetruesteepname** [comment]
будет некорректно смотреться, ибо нет таких аксессуаров, которые будут корректны на трех ста скинах

**Comment by ziggi** [comment]
Возможно, в будущем добавлю, пока эти "рюшечки" ни к чему.
