### ISSUE TITLE
Возможность включать спектатор обычным игрокам

### ISSUE THREAD

**Issue by ziggi** [ziggi/Open-GTO#25]
Добавить возможность включать спектатор обычным игрокам, по умолчанию выключено.

**Comment by thetruesteepname** [comment]
хоть и по умолчанию это выключено, но это позволит без препятствий следить за вражескими бандами, что они делают, где находятся, возможно смотреть различные тактики, хоть это конечно и сделано, чтобы наказывать нечестных, но это сможет стать само по себе нечестным

**Comment by ziggi** [comment]
Верно, да и пользы от функции нет.
