### ISSUE TITLE
Добавить анти Drive By

### ISSUE THREAD

**Issue by ziggi** [ziggi/Open-GTO#36]
Добавить анти драв бай.

**Настройки:**
- 0 — выключить;
- 1 — включить (игрок не может стрелять с водительского места);
- 2 — включить (при убийстве с транспорта автоматически садило на некоторое время в тюрьму, время сделать опциональным).

**Comment by thetruesteepname** [comment]
это уже совсем не весело, прям РП, а не помесь с ДМ'ом, лучше это связать как-то с #32, не более, потому что если такое будет, это будет очень и очень плохо

**Comment by ziggi** [comment]
Решил просто уменьшить урон, наносимый из транспорта.

**Comment by ziggi** [comment]
Решил просто уменьшить урон, наносимый водителем из транспорта.
