### ISSUE TITLE
Теги для банд

### ISSUE THREAD

**Issue by ziggi** [ziggi/Open-GTO#63]

**Comment by thetruesteepname** [comment]
можно сменить имя на имя с тегом банды, лично когда я беру кого-нибудь в банду, я не всегда хочу чтобы он имел тег моей банды, да и тут уже могут быть такие глупости как некорректные имена банд, начиная от обычного набора букв, заканчивая матом, да и когда будет много народа, будет сложно различать людей

**Comment by ziggi** [comment]
Согласен, тем более теги могут причинить множество хлопот в техническом плане.
